### ISSUE TITLE
Persist broadcasting state.

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#116]
## Problem Definition

The request collector is currently not remembering its state of the broadcasting room. Bet as @ulope  said there is a way to do that, so we should do it:

> But the ‘correct’ solution is to remember the client’s .sync_token and restore that on the next run

**Comment by palango** [comment]
@andrevmatos Can you give us some input here? Is remembering the `sync_token` enough to remember what message was last received??

**Comment by andrevmatos** [comment]
This is... complicated. The correct solution for stateful matrix client is to actually serialize and persist the whole state (rooms, presences, displaynames, tags, aliases, everything),  restore it, and only then proceed with the previous `sync_token`. This is what is done by [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/client.js#L223), but matrix-python-sdk isn't quite designed to serialize/restore the state. If you persist the `sync_token` only, you'll have problems, because state deltas will start being applied over a different state than before, which **will** give unpredictable results. The alternative is what we do now: always perform an `initialSync` on start, which brings the whole state from server, and fetches only a batch of the last messages altogether, which may or may not have been already processed, or may or may not contain all messages since previous sync. Doing an initialSync then proceeding with last/persisted `sync_token` is still problematic, as you'll be applying old state deltas over an up-to-date state.
So, either:
- Long/correct path: check on how to persist whole state, and then persist/resume old `sync_token`
- Current approach: treat matrix as kind of a volatile transport, always perform `initialSync`, and try your best to load old enough messages, guaranteeing idempotency for duplicated events.

**Comment by palango** [comment]
Thanks @andrevmatos for the thorough explanation.

Is the `initialSync` done automatically by the functions we use now or do we need to trigger this explicitly?

**Comment by andrevmatos** [comment]
@palango it's done currently by [raiden.network.transport.matrix.utils::login_or_register](https://github.com/raiden-network/raiden/blob/3cf5430c19f399f7dcb89a7c110729e47235b7d4/raiden/network/transport/matrix/utils.py#L144-L146), with number of fetched old messages on initialSync == `0` (as we can't know if they were already processed, then trully treating matrix as an ephemeral transport).
If you can ensure idempotency, this number of old messages could be parametrized as well, possibly with some store for last already processed message and skipping before it, or something like that.

**Comment by karlb** [comment]
The current solution is acceptable considering that the Request Collector is not frequently restarted. Also, changing the behavior seems to be difficult with the Matrix SDK we currently use.
