### ISSUE TITLE
Discussion about different designs of monitoring services

### ISSUE THREAD

**Issue by SamAI-Software** [raiden-network/raiden-services#145]
Links:
- [The original discussion](https://github.com/raiden-network/raiden-monitoring-service/issues/30) from the archived repository.
- [The first article](https://medium.com/crypto-punks/lightning-vs-raiden-can-watchtowers-and-monitoring-services-scale-c8eb0f724e68) about differences between LN watchtowers and RDN monitoring services and main challenges.
- [The second article](https://medium.com/crypto-punks/lightning-vs-raiden-2-can-we-solve-privacy-and-scalability-problems-of-watchtowers-and-e243f7793d19) about solutions and their trade-offs.

**Business models**

I'm currently researching accountability and business models of watchtowers and monitoring services for the third, and hopefully, the last article in the series. Here are some possible monetization strategies:

1. Altruistic watchtowers (no compensation at all)
2. Compensation from each punishment transaction that was broadcasted (or in case of RDN, for each stopped settlement)
3. Monthly or annual subscriptions
4. One-time fee for the amount of state updates to be stored (in current LN's design watchtowers store all previous state updates)
5. A periodic fee for each stored state update
6. Periodic subscription for the amount of bandwidth

Each approach has its pros and cons. What is the current plan for monitoring services to monetize their services in order to cover operating costs?

**Accountability**

And is there any work on accountability issue? There are at least 3 different approaches:

1. Financially incentivize monitoring services to dispute malicious settlements via direct reward in case of a successful dispute.
2. Reputation systems.
3. Collateral (deposit/stake) that a monitoring service will lose if it fails to stop an attack.

Which one are you planning to implement?

**Comment by palango** [comment]
Hi Sam,

> Each approach has its pros and cons. What is the current plan for monitoring services to monetize their services in order to cover operating costs?

The current design is a compensation for each on-chain update (it's not a punishment, but the non-closing party needs to send it's side of the state in any case). This means that the Monitoring Service that submits the latest *successful* call to `updateNonClosingBalanceProof`  is able to claim a reward. This means that it is the MS that set the state to the latest off-chain state who gets the reward. In case two or more MS want to submit the same update only the first one will succeed; this might be a problem so we're looking into creating some ordering in which the MS can act.
The reward is user chosen, so each MS needs to decide if the reward is sufficient to take action.

See also https://raiden-network-specification.readthedocs.io/en/latest/service_contracts.html#monitoringservice

Remember also that settlement cannot be stopped. The update only makes sure that settlement is done with the correct values, but the settlement period is never prolonged and settlement can only be done when the correct values according to the closing balance proofs are provided.


> Which one are you planning to implement?

There might be several different designs implemented in the future. Also your articles and the discussions help us to find better designs.

However, for now we implement option 1), so the MS has an incentive to do the on-chain update in order to receive its reward.


Hope this answers your questions. Let us know if there are more questions and/or something in the spec is unclear.

**Comment by SamAI-Software** [comment]
Thanks for your answers! The third article has been published, you can find it [here](https://medium.com/crypto-punks/lightning-vs-raiden-watchtowers-accountability-business-models-celer-pisa-833384f01ad0).
