### ISSUE TITLE
Remove `monitor_address` from MonitorRequest

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-services#20]
The current plan is to broadcast MonitorRequests to all registered MS via Matrix. With this in mind, having a specific `monitor_address` makes no sense.

- [x] check if spec needs update
- [x] wait for monorepo
- [x] remove `monitor_address` and all of its usages in a single PR

**Comment by SamAI-Software** [comment]
Do you mean by "MonitorRequest" an initial request to start using monitoring services, or a package that will be sent to MSs after each channel state update?
If you mean the latter, then can you specify what are the main advantages of this approach?

I'm asking about the pros, because there are certain cons, e.g.:
There are some privacy plugs like MS rotation, so user will have a list of e.g. 3-10 MSs and will randomly send state updates (balance proofs) to one MS from the list after each off-chain transaction. Of course, this feature will not increase privacy if there will be a big network of obedient MSs, since they will collude, but rotating MSs will make global surveillance much harder.

**Comment by Dominik1999** [comment]
@SamAI-Software this could also help you - we updated the Monitoring Service Spec (still it is under development, but could clarify some things)
https://raiden-network-specification.readthedocs.io/en/latest/monitoring_service.html

**Comment by Dominik1999** [comment]
@karlb in the spec, the monitor_address is not part of the monitor request.

**Comment by palango** [comment]
@SamAI-Software 

> Do you mean by "MonitorRequest" an initial request to start using monitoring services, or a package that will be sent to MSs after each channel state update?

With the current design you need to send a reward for every BP that you want to be monitored. However, only one reward will be payed out (the the submitter of the latest BP). If it gets sent for every channel update will be a policy of the client (but it would make sense IMO).
