### ISSUE TITLE
MS: force a deterministic order of MS interactions

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#287]
Currently all MS compete on sending the call to `monitor` on-chain. There are ideas about forcing a deterministic order, to potentially lower costs.

**Comment by karlb** [comment]
Previous discussion on this topic in https://github.com/raiden-network/spec/issues/46.

The most specific suggestions are:
> The coodination also could be done with an auction-based reward where the reward starts at x % of the amount user wants to pay and then the amount increases as the end of the settlement period is approaching. This can naturally reach an equilibrium state where actors wait until the reward reaches the cost for running the MS.

> regarding the order in which the MSs will send the transaction that will update the user’s balance proof, this must be enforced by the MSC and can use block distance - allow an MS to send the transaction only between certain block values (e.g. MS1: closing_channel_block -> closing_channel_block + 5, MS2: closing_channel_block + 5 -> closing_channel_block + 10 etc.);

**Comment by karlb** [comment]
Instead of the second suggestion, I would prefer something that does not require the full list of MSs and allows all MSs to act near the end of the settlement period. We could calculate at which point between closing and settlement timeout a MS is allowed to act by doing
```python
offset = (ms_address + p1_address + p2_address) modulo (settlement_timeout / 2)
allowed = close_block + settlement_timeout / 2 + offset < current_block
```
This would prevent all MSs from acting during the first half of the settlement period so that the client can settle himself. Then after a pseudo-random (based on the MSs address) point in time during the remaining settlement period, each MS is allowed to act.

**Comment by pirapira** [comment]
Sounds good. (Just one comment: calling it "pseudo-random" would probably gather online trolls.  Getting a good, onchain random number is a known [hard](https://github.com/randao/randao) [challenge](https://ethresear.ch/t/minimal-vdf-randomness-beacon/3566).)

**Comment by karlb** [comment]
Since we don't actually know the `close_block`, we'll assume `close_block = settle_block_number - settlement_timeout_min`. The `settlement_timeout_min` is currently set to 500, which should be enough to make this work acceptably.

**Comment by pirapira** [comment]
I see.  That's a bit hacky but saves gas in TokenNetwork.
