### ISSUE TITLE
Add persistent database

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#63]
## Problem Definition

Currently the MS used a simple in-memory database. This should be replaces with a proper sqlite version that persists the state on disk.

- [x] save and load state to/from db instead of keeping data inside `Database`
- [x] initialize db properly and check parameters when db is already present
- [x] use proper pkey for saving/loading MRs (non_closing_signer is missing)
- [x] Use the same MR object in MS and request collector
- [x] Reduce state related code duplication between MS and request collector 
- [x] test that loading data after saving results in the same data
- test that MS works properly after crashing during processing a block (will be done as part of #32)

13 SP

**Comment by karlb** [comment]
- [x] save and load state to/from db instead of keeping data inside `Database`
- [x] initialize db properly and check parameters when db is already present
- [x] use proper pkey for saving/loading MRs (non_closing_signer is missing)
- [ ] Use the same MR object in MS and request collector
- [ ] Reduce state related code duplication between MS and request collector 
- [ ] test that loading data after saving results in the same data
- [ ] test that MS works properly after crashing during processing a block
