### ISSUE TITLE
Service monitoring/Dashboard

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#7]
## Raiden Service Bundle operators want to see metrics of their services
The Raiden Services, Pathfinding and Monitoring, are being operated by external providers. Those providers want to see a dashboard showing relevant and interesting information. The dashboard can be in parts but should not be in general publicly accessible. 

## Get familiar with the Raiden Service Bundle
- Specification of the Monitoring Service https://raiden-network-specification.readthedocs.io/en/latest/monitoring_service.html
- Specification of the Pathfinding Service https://raiden-network-specification.readthedocs.io/en/latest/pathfinding_service.html
- Services Repo on GitHub https://github.com/raiden-network/raiden-services

## Plan in detail
Please plan this issue here in small steps such that implementation can be iterative. Please sketch a design of the dashboard and the necessary inputs first. 

Bonus: Our colleagues from eth.events, our community manager Boris and our friends from dappNode can give you feedback or ideas which information should be shown on the dashboard. @czepluch can provide contacts.

this was initially planned by the team https://github.com/raiden-network/raiden-services/issues/7#issuecomment-635385656

- [ ] Sketch a design of the dashboard - what data should we show there?
- [ ] From the data, deduct the necessary endpoints in the PFS and MS
- [ ] ...

++++++
Original Issue
The running PFS should provide some insights, e.g. requests per minute, network topology...

Users want to see how many requests were processed and how many IOUs collected. Maybe we can create an easy and secure endpoint for that?

**Comment by palango** [comment]
It might make sense to talk to Nils about that and maybe implement a prototype while he is still in Berlin.

**Comment by ulope** [comment]
Since we already use Prometheus in a couple of places it would make sense to continue that here. 

The Python client library is also pretty easy to use.

**Comment by konradkonrad** [comment]
- specify what data to provide
- create a `_stats` or the like endpoint

**Comment by ulope** [comment]
Depending if we want to go with prometheus or provide a generic api endpoint that can then reformatted the python client library could be helpful to get something working quickly: https://github.com/prometheus/client_python

**Comment by fredo** [comment]
- [ ] Talk to the current providers what kind of metrics are desired
- [ ] investigate prometheus approach (maybe with the help of @ulope @nlsdfnbch )
- [ ] new docker container in docker-compose set up 
- [ ] accessible by new subdomain

**Comment by nlsdfnbch** [comment]
I'd suggest going with the prometheus library as well - it's simple enough to get going. If you do not want the dependency though, you might want to consider the the OpenMetrics format (which is influenced by prom's format and also supported by it). There's a workgroup for it, with a repo [here](https://github.com/OpenObservability/OpenMetrics).

**Comment by ezdac** [comment]
After analysing the code and evaluating some solutions I came up with an initial plan-to-action:

# Problem
We want to create endpoints for the Raiden Service Bundle, so that especially the operator of the service-nodes has some insight in runtime metrics of the system. This includes operational metrics (*RED* mentioned above), but also metrics regarding the economics (earnings) of a node as well as e.g. network topology metrics.

Most of the data we want to expose is *numerical* (node economics, request counts) and simple, flat *key-value* data, and we might want to observe this data over time (*time-series*) as well as accumulated over the value range (*statistical distribution*).  We don't expect to expose complicated, nested data-structures at the time.
 
# Tooling
As suggested above, the **Prometheus** seems to be an easy to implement solution for this kind of data, since with the `Counter`, `Histogram`, `Summary`,`Info` and `Enum` classes the expected data-types are covered.
Labels and namespaces allow to define and describe the metrics.
Graphing software like Grafana has built-in Prometheus integration, so it is easy to create Dashboards to monitor the metrics that are exposed. The metrics can be collected from different Prometheus "clients", so it is easy to have a one universal "Plug-In" dashboard for all of the individual components of the Raiden Service Bundle, even when they run on different servers, or when only a subset of Services is connected.

# Constraints for first iteration
- For now, only expect the node operator to query the API, so expect it to be non-public
- Expose data that is easy to collect from the current code / database. Don't create involved methods calculating metrics.

# Sample code

The metrics should be defined in a separate location:
#### Define the metrics
```python
# metrics.py
from prometheus_client import Counter

REWARD_CLAIMS_TOKEN = Counter(
    "economics_rewardclaims_token",
    "The amount of token earned by reward claims",
    labelnames=["who"],
)

REWARD_CLAIMS = Counter(
    "economics_rewardclaims",
    "The number of overall successful reward claims",
    labelnames=["who"],
)

ERRORS_LOGGED = Counter(
    "logs_errors",
    "The number of errors that where written to the log.",
    labelnames=["kind"],
)


```

#### Increase counter for logged errors
``` python
# Count the number of logged errors and categorize them by some labels
        failed_at = context.web3.eth.blockNumber
        log.error(
            "Sending tx failed",
            exc_info=True,
            err=exc,
            first_allowed=first_allowed,
            failed_at=failed_at,
        )
        metrics.ERRORS_LOGGED.labels(kind="blockchain").inc()
        return
```

#### Increase reward claim counters

Here we can increase e.g. the number of succesful reward claims and the total number of 
amount claimed. The metric could easily be changed to a `Histogram`, so that we can also observe the 
reward distribution over time.
The labels `us` and `they` allow us to e.g. also log the rewards we wanted but we didn't get.
```python
    if event.ms_address == context.ms_state.address:
        log.info(
            "Successfully claimed reward",
            amount=event.amount,
            reward_id=event.reward_identifier,
        )
        metrics.REWARD_CLAIMS.labels(who="us").inc()
        metrics.REWARD_CLAIMS_TOKEN.labels(who="us").inc(event.amount)
    else:
        log.debug(
            "Another MS claimed reward",
            amount=event.amount,
            reward_id=event.reward_identifier,
        )
        metrics.REWARD_CLAIMS.labels(who="they").inc()
        metrics.REWARD_CLAIMS_TOKEN.labels(who="they").inc(event.amount)

```

The Prometheus endpoint can be easily plugged in the existing API-infrastructure, so that it can be served from an additional endpoint, e.g. `/metrics`:

```python
        # Add the metrics prometheus app
        self.flask_app = DispatcherMiddleware(
            NotFound,
            {API_PATH + "/metrics": make_wsgi_app(registry=metrics.REGISTRY), API_PATH: flask_app.wsgi_app,},
        )

```

# WIP Metrics

This is a (possibly incomplete) list of metrics that should be exposed for the first (and later) iterations.
## Monitoring service

## Request collector
Here we have to evaluate if it is necessary to expose metrics of the request collector, since there is not that much information that can be gathered. 
There currently is no API exposed for the request collector, so make sure that if we want to expose metrics it is worth / secure to expose an API (@karlb maybe you can give some insight).

- Number of invalid MonitoringRequests received from the transport (no signature, mismatching signature, channel known and closed already) - this information will not propagate to the monitoring service and would be "lost" if not collected (apart from the logs of course)
- Request processing time metrics
- Node state (running, stopped)

## Pathfinding service

## Matrix listener

**Comment by deepbrook** [comment]
Have a look at https://metrics.brainbot.com. It;s a prometheus/grafana/alertmanager instance. 
Its configuration is hosted here: https://github.com/brainbot-com/metrics.brainbot.com

**Comment by karlb** [comment]
> There currently is no API exposed for the request collector, so make sure that if we want to expose metrics it is worth / secure to expose an API

The data collected by the RC is available to the MS, so I don't see the need to add an additional API.

**Comment by Dominik1999** [comment]
Thank you for this issue @ezdac ! I like the detailed planning and it helps me to follow your thought and design process. 

For the metrics itself, I would start with 

- RED metrics on the pathfinding (PFS) and monitoring service (MS)
- 2 economic data points for the PFS and MS, total collected IOUs and total claimed IOUs

With this starting point, we should be able to improve based on user feedback.

Do you think we can have something ready on Friday 14of August?

**Comment by ulope** [comment]
Thank @ezdac, overall this looks very good!

Some things to consider:
- The naming of the metrics should follow the [prometheus naming conventions](https://transport.mainnet.raiden.anyblock.tools/_matrix/client/versions)
- The metrics classes exposed by the prometheus python client can be used as both decorators and context managers this may make the implmentation easier in some parts (see the [README](https://github.com/prometheus/client_python) for examples). 
- I would suggest to include the token network registry address as a label in all relevant metrics. That way we can use counters for most metrics that would otherwise have to be gauges (e.g. `token networks`, `closed channels`).
- The prometheus python client library has some limitations when a server is running in multiprocess mode (see README). This isn't currently the case for any of the services but we should keep it in mind as we probably will want to move in that direction at some point.
- We should consider if we want to expose the metrics endpoint alongside the regular API server or if we should run it on a separate one, to allow controlling access independent of a possibly existing reverse proxy.

**Comment by ezdac** [comment]
Thanks @ulope for the input!
Regarding the Reverse Proxy, I can't really comment on that.
What would be the use-case of not using the same environment for the metrics API? Circumventing rate-limiting of the public API?

If you think it should be separate I am fine with implementing this.

**Comment by ulope** [comment]
I guess it's not too important at the moment. Let's go with the easiest option for now.
