### ISSUE TITLE
Provide release version PFS deployments

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#80]
## Problem Definition

For testing purposes we want to provide services of the latest released version as well as current master.

**Comment by nlsdfnbch** [comment]
In order to supply a `latest` and `master` version, you will have to supply a Dockerfile, which will be built via Dockerhub.

I would suggest using build/run args to keep the image customizable, otherwise you'd have to build several different images, one for each chain/config combination.

Once you have done so, I can set up hooks on docker hub to build these files.

`latest` is typically built on the latest commit on `dev`, whereas `master` is typically the latest pushed `tag`. If that does not suit you, let me know how you'd like it to be configured.

**Comment by palango** [comment]
There is a dockerfile in the repo: https://github.com/raiden-network/raiden-services/blob/master/Dockerfile

If necessary please update that as well. I guess for now we'd only need to add a build arg for the version of the services to install. Everything else could stay a run arg in my opinion.

**Comment by nlsdfnbch** [comment]
That will require a bit more than a build arg, since that does not even define an Entry point/cmd step.

Please specify the args required to run the service, and the args you'd like to bake-in/have customizable.

Also, will different images be required for each service? If not, I will have to accept a build_arg to set the environment vars (I believe you do set that via env vars, iirc?)

**Comment by palango** [comment]
The docker-compose file is here: https://github.com/raiden-network/raiden-services/blob/master/deployment/docker-compose.yml

We don't have an entry point because there are multiple services in the same image.

To keep in mind: the installation guide/package will add further requirements (like running the registration script). See https://github.com/raiden-network/raiden-services/pull/438 for that

**Comment by karlb** [comment]
This corresponds to https://github.com/raiden-network/team/issues/591.
