### ISSUE TITLE
Manage connection pool better

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-services#84]
## Problem Definition

When running the PFS on a registry with many registered token it logs many errors like the following:
```
02-07 15:57:49 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: parity.kovan.ethnodes.brainbot.com
```

## Actual Outcome

A lot of connections are discarded.

## Expected Outcome

The connection pool should be managed better or increased in size.

**Comment by schmir** [comment]
We've ran into the same problem in the trustlines project [1]. We're interested in any insights. It would be nice  if you could write them down here. 

[1]  https://github.com/trustlines-network/relay/issues/246 . Though we didn't really investigate how to solve it.

**Comment by hackaugusto** [comment]
This is not a problem at all, the pool is an optimization to reuse sockets. New connections are still made but not added to the pool if the capacity has been reached (however, this is configurable).

The point is, either you don't benefit from the pool because you need many connections, or there is a piece of code that opens too many short lived connections in a short life span. This is what happened with https://github.com/raiden-network/raiden/issues/1847

**Comment by palango** [comment]
The warnings have been suppressed in #104 . We still need to investigate and come to a conclusion on this issue.

**Comment by palango** [comment]
This doesn't happen any more with #230
